
#!/bin/bash


# Backup Source Directory

SOURCE_DIRS=(
"/home/guna/shell-projects-temp/02-Automated-Backup-Cleaning-System/source/app1"
"/home/guna/shell-projects-temp/02-Automated-Backup-Cleaning-System/source/app2"
"/home/guna/shell-projects-temp/02-Automated-Backup-Cleaning-System/source/database"
)

# Backup Destination Directory

BACKUP_DIR="/home/guna/shell-projects-temp/02-Automated-Backup-Cleaning-System/backups"

# Log File Location

LOG_FILE="/home/guna/shell-projects-temp/02-Automated-Backup-Cleaning-System/logs/backup.log"

# Number of days to keep backups

RETENTION_DAYS=10
